# Generated by Django 4.2.10 on 2024-02-11 22:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('sell', 'sell'), ('buy', 'buy')], max_length=150)),
                ('operation_date', models.DateField()),
                ('n_stock', models.FloatField()),
                ('price', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.user')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=150)),
                ('n_stock', models.FloatField()),
                ('avg_price', models.FloatField()),
                ('industry', models.CharField(max_length=150)),
                ('n_stock_next_exdiv_payment', models.FloatField()),
                ('next_exdiv_payment', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.user')),
            ],
        ),
        migrations.CreateModel(
            name='DividendPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=64)),
                ('payment_date', models.DateField()),
                ('amount', models.FloatField()),
                ('n_stock', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.user')),
            ],
        ),
    ]
