# Generated by Django 4.2.10 on 2024-02-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='next_exdiv_payment',
            field=models.DateField(),
        ),
    ]
