# Generated by Django 4.2.10 on 2024-02-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_user_password_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ticker',
            field=models.CharField(default='', max_length=64),
        ),
    ]
