name: run pay_div_endpoint.py

on:
  schedule:
    - cron: '0 2 * * *' # At 02:00 every day

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed
          
      - name: install python packages
        # pip install -r requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install requests==2.28.1

          
      - name: execute py script # run main.py
        env:
          ENPOINT_DIV: ${{ secrets.ENPOINT_DIV }}
        run: python portfolio/cron_jobs/pay_div_endpoint.py
          
      # - name: commit files
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git add -A
      #     git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      # - name: push changes
      #   uses: ad-m/github-push-action@v0.6.0
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: main 